Feature #2358 NAT64 Support
pfsense/pfsense pull request #4405
Opened 2020-07-22 02:59 UTC by nickwhaley

- [X] Redmine Issue: https://redmine.pfsense.org/issues/2358
- [X] Ready for review

I've looked into this. Looks like there are 3 possible approaches.

1) Use the Packet Filter (PF) implementation. OpenBSD has implemented this, but after FreeBSD branched from it. It would require porting and re-implementing NAT64 in the FreeBSD branch. I have not looked into how difficult that would be.

2) Use Tayga as a package. I have installed the FreeBSD build of Tayga and it appears to work fine. It runs in user mode and is fairly independent from the rest of pfSense.

3) Use IPFW's NAT64 kernal module. IPFW is already installed (I think for Captive Portal? And traffic shaper?) and I have copied ipfw_nat64.ko from FreeBSD 11.3, loaded it, and it also appears to work fine right out of the box.

Went with IPFW (3) as it seems to be the cleanest. A few system-level things I need reviewed though:

1) The kernal module ipfw_nat64 needs to be added to the build. Edited builder_defaults.sh for this.

2) A few sysctl settings need to be set. IPFW needs to be enabled as a pfil.

3) Not that familiar with all the Capture Portal and traffic shaper use cases, so not sure how to test interaction. But did make sure the capture portal rules used a different set of rule numberings.

4) For UI elements, put them under Firewall -> NAT -> NAT64

5) For testing this, do make sure you have Firewall -> Rules to allow for the translated traffic.

2020-07-22 11:35 UTC, rbgarga commented
@nickwhaley 2.4.5 will not get such a big change, please submit PR against master branch, what is today 2.5.0-DEVELOPMENT

2020-07-22 20:15 UTC, nickwhaley commented
Figured out how to setup and test Captive Portal since it also uses ipfw. Looks to be interacting badly, will fix.

2020-07-23 14:31 UTC, nickwhaley commented
Conflicting issues with captive portal fixed.

2020-07-27 20:06 UTC, User-042 commented
First an foremost thank you for creating a NAT64 feature!
I tried to install this patch and got an error:

**|diff --git a/tools/builder_defaults.sh b/tools/builder_defaults.sh
|index c46d03a14d2..36070a55a9e 100644
|--- a/tools/builder_defaults.sh
|+++ b/tools/builder_defaults.sh

No file to patch. Skipping...
Hunk #1 ignored at 137.
1 out of 1 hunks ignored while patching builder_defaults.sh
done**

If any one can help that would be great!
This is also my first time using patches do any help would be great ;)

2020-07-27 20:12 UTC, nickwhaley commented
@User-042 

builder_defaults.sh is for the tools to build a pfSense release. It will not exist when installed.

If you are applying this patch to an existing pfSense install, you will need to acquire the corresponding FreeBSD version of your pfSense install and copy the `/boot/kernal/ipfw_nat64.ko` module manually.

2020-07-27 20:32 UTC, User-042 commented
How would i go about doing that?

2020-07-28 02:33 UTC, nickwhaley commented
@User-042 https://www.freebsd.org/where.html

2020-08-02 07:47 UTC, vktg commented
IPFW NAT64 kernel support PR:
https://github.com/pfsense/FreeBSD-src/pull/35

2020-09-05 12:01 UTC, vktg commented
- It passes traffic only if you set `net.inet.ip.fw.nat64_direct_output=1`,
from ipfw(8):
```
net.inet.ip.fw.nat64_direct_output: 0
	     Controls the output method	used by	ipfw_nat64 module:

	     0	     A packet is handled by ipfw twice.	 First time an origi-
		     nal packet	is handled by ipfw and consumed	by ipfw_nat64
		     translator.  Then translated packet is queued via netisr
		     to	input processing again.

	     1	     A packet is handled by ipfw only once, and	after transla-
		     tion it will be pushed directly to	outgoing interface.
```
see also https://forums.freebsd.org/threads/nat64-with-ipfw-issues.70366/

- It should set the prefix netmask in all cases, now if you set it to /32 it will skip it from the command arg:
```
# /sbin/ipfw -q nat64lsn NAT64_0 create prefix4 1.2.3.4 prefix6 64:ff9b::/96
ipfw: Prefix length required
```

tested on 2.5.0.a.20200904.1850 with `ipfw_nat64` module

2020-09-08 21:54 UTC, rbgarga commented
> * It passes traffic only if you set `net.inet.ip.fw.nat64_direct_output=1`,
>   from ipfw(8):
> 
> ```
> net.inet.ip.fw.nat64_direct_output: 0
> 	     Controls the output method	used by	ipfw_nat64 module:
> 
> 	     0	     A packet is handled by ipfw twice.	 First time an origi-
> 		     nal packet	is handled by ipfw and consumed	by ipfw_nat64
> 		     translator.  Then translated packet is queued via netisr
> 		     to	input processing again.
> 
> 	     1	     A packet is handled by ipfw only once, and	after transla-
> 		     tion it will be pushed directly to	outgoing interface.
> ```
> 
> see also https://forums.freebsd.org/threads/nat64-with-ipfw-issues.70366/
> 
> * It must set the prefix netmask in all cases, now if you set it to /32 it will skip it from the command arg:
> 
> ```
> # /sbin/ipfw -q nat64lsn NAT64_0 create prefix4 1.2.3.4 prefix6 64:ff9b::/96
> ipfw: Prefix length required
> ```
> 
> tested on 2.5.0.a.20200904.1850 with `ipfw_nat64` module

@nickwhaley I've committed the chance on builder_defaults.sh to make it to build ipfw_nat64 kernel module on snapshots to it's easier for testing.

Can you please fix the issues mentioned above by @vktg so we can do a final review/testing and get it merged?

2020-09-09 16:36 UTC, nickwhaley commented
@rbgarga Will take a look at that.

2020-10-12 12:15 UTC, rbgarga commented
> @rbgarga Will take a look at that.

@nickwhaley we are working to release 2.5.0 in a near future.  Do you have plans to work on this patch soon? Otherwise I can move redmine ticket to a future release

2020-10-12 12:23 UTC, idarlund commented
this is a critical issue for us ipv6 users, please include this in the 2.5.0 release. @nickwhaley @rbgarga

2020-10-14 15:49 UTC, nickwhaley commented
@rbgarga Will push by the end of the week

2020-10-14 23:58 UTC, nickwhaley commented
@vktg Regarding `net.inet.ip.fw.nat64_direct_output=1`. I am not finding this to be required to pass traffic.

The problem with enabling that is that you no longer can filter any of the NAT64 traffic as all of it bypasses the PF firewall rules with this on (and be firewall software without firewalling). In addition you will loose the ability to NAT44 the output if you have native IPv4 subnets in addition to your NAT64 subnets.

It may be that you need PF firewall rules that match the result AFTER translation (similar to how NAT44 works) or else it will drop it. Please make sure that works to pass traffic for you. I.E. NAT64 `64:ff9b::/96` -> `10.0.6.0/24` you need a accept source net `10.0.6.0/24` on the IPv6 side and accept source net `64:ff9b::/96` on the IPv4 side.

If so, I have a few ideas to mitigate that:

- Create a bold note in the NAT64 Edit to advise to create firewall rules to allow traffic.
- Implicitly allow all NAT64 traffic by automatically generating the rules.
- Enable `net.inet.ip.fw.nat64_direct_output=1` and loose the complexity of rules on top of translation. But also loose the ability to firewall the NAT64 traffic.

2020-10-16 18:06 UTC, nickwhaley commented
@vktg @rbgarga

Ended up doing combination of A and B. I really didn't want to lose the ability to apply PF firewall rules to this traffic, so `net.inet.ip.fw.nat64_direct_output` remains OFF. There is a note on the firewall rules required and some implicit rules for outbound nat-ed data.

The issue with /32 rules is also fixed. Should be ready for review.

2020-10-16 18:11 UTC, rbgarga commented
> @vktg @rbgarga
> 
> Ended up doing combination of A and B. I really didn't want to lose the ability to apply PF firewall rules to this traffic, so `net.inet.ip.fw.nat64_direct_output` remains OFF. There is a note on the firewall rules required and some implicit rules for outbound nat-ed data.
> 
> The issue with /32 rules is also fixed. Should be ready for review.

Awesome! Thank you!

@vktg can you re-do the tests please?

2020-10-17 15:23 UTC, vktg commented
tested on 2.5.0.a.20201016.1850

> The issue with /32 rules is also fixed. Should be ready for review.
Works.

> It may be that you need PF firewall rules that match the result AFTER translation (similar to how NAT44 works) or else it will drop it. Please make sure that works to pass traffic for you. I.E. NAT64 `64:ff9b::/96` -> `10.0.6.0/24` you need a accept source net `10.0.6.0/24` on the IPv6 side and accept source net `64:ff9b::/96` on the IPv4 side.

Works as expected!

But I found another weird issue - if you put your WAN IP in the IPv4 address field, it blocks any ingress/egress IPv4 traffic on it.
You can't ping any outside IPs from pfSense, Outbound NAT stops working..
Maybe some special rules needed or is this by design?

p.s. optional todo: Diagnostics / NAT64 states (for `ipfw nat64lsn all show states`)

2020-10-19 11:47 UTC, rbgarga commented
> tested on 2.5.0.a.20201016.1850
> 
> > The issue with /32 rules is also fixed. Should be ready for review.
> > Works.
> 
> > It may be that you need PF firewall rules that match the result AFTER translation (similar to how NAT44 works) or else it will drop it. Please make sure that works to pass traffic for you. I.E. NAT64 `64:ff9b::/96` -> `10.0.6.0/24` you need a accept source net `10.0.6.0/24` on the IPv6 side and accept source net `64:ff9b::/96` on the IPv4 side.
> 
> Works as expected!
> 
> But I found another weird issue - if you put your WAN IP in the IPv4 address field, it blocks any ingress/egress IPv4 traffic on it.
> You can't ping any outside IPs from pfSense, Outbound NAT stops working..
> Maybe some special rules needed or is this by design?
> 
> p.s. optional todo: Diagnostics / NAT64 states (for `ipfw nat64lsn all show states`)

Thanks for testing this!  Lets wait to hear from @nickwhaley regarding your concerns.

2020-10-19 14:53 UTC, nickwhaley commented
> But I found another weird issue - if you put your WAN IP in the IPv4 address field, it blocks any ingress/egress IPv4 traffic on it.

This is by design of the IPFW NAT64 module. Any traffic not matching a NAT64 state on the IPv4 address(s) will be dropped. I imagine that NAT64 cannot be combined with regular IPv4 without possible overlapping states. Not sure anything can be done about that.

But, this can be addressed by either reserving a IPv4 address specifically for NAT64. OR by creating a NAT64 mapping to an internal address range, then create a NAT44 mapping from those addresses to your WAN address.

2020-10-22 12:45 UTC, rbgarga requested changes

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> + * Copyright (c) 2020 Nick Whaley
Did you copy this file from other and made few changes?  If your answer is yes, then nevermind.  If you wrote all this code from scratch you should remove BSD Perimeter and Electric Sheep Fencing copyright notices and change Rubicon line from 2014-2020 to only 2020

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> + * All rights reserved.
Same question here, if you copied content from a file that already had this copyright and changed just a few of it, OK, if you changed like 80/90% then you can remove it

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> +	));
There are some indentation issues here.  First lines are using TABs only and last ones are using mixed TABs and spaces

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> +	$a_nat64 = &$config['nat']['nat64']['rule'];
You are not modifying content of `$a_nat64` so it doesn't need to be assigned as a reference

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> +		nat64_syslog("Out of space for nat64 rules. Some may be ignored.");
pfSense style: Always use brackets on conditionals, even if it's a single sentence inside it
```php
if (foo) {
    bar();
}
```

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> +			if (strpos($ip4, '/') === FALSE) $ip4 .= '/32';
pfSense style: Always use brackets

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> +			//if (strpos($ip6, '/') === FALSE) $ip6 .= '/128'; //ipv6 prefix cannot be 128 bits long (RFC6052)
Remove commented out line

2020-10-22 12:45 UTC, rbgarga commented on src/etc/inc/nat64.inc
> +		if (empty($existingRule) && $i >= count($a_nat64)) break;
pfSense style: Always use brackets

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64.php
> + * nat64.inc
Wrong filename

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64.php
> + * All rights reserved.
Same comments I made on nat64.inc.  If you copied and changed few, keep it, otherwise, clean it up

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64.php
> +	if (is_array($_POST['rule']) && !empty($_REQUEST['rule'])) {
Both if conditionals can be merged into a single one

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64.php
> +	if ($a_nat64[$_POST['id']]) {
Both ifs can be merged into a single one

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64.php
> +					gettext('The changes must be applied for them to take effect.'));
pfSense style: Multiline statements are indented using 4 spaces after previous like indentation

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64_edit.php
> + * All rights reserved.
Same comments of nat64.inc

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64_edit.php
> +//$pconfig['icmp_age'] = 60;
Delete commented out lines

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64_edit.php
> +		$dummyvar, $dummyvar, $dummyvar);
Style: Multiline statements are indented using 4 spaces after previous line indentation

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64_edit.php
> +		$input_errors[] = gettext("The Well-Known IPv6 Prefix 64:ff9b:: must be 96 bits long.");
Style: Always use brackets

2020-10-22 12:45 UTC, rbgarga commented on src/usr/local/www/firewall_nat_nat64_edit.php
> +			$_POST['prefix6'] = trim($_POST['prefix6']);
Style: Always use brackets

2020-11-12 20:57 UTC, frebib commented
I've been using this for a few days now (after 2 days of head-scratching at firewall rules) and it seems to work pretty well.
The one thing I think would be an improvement would be an `enable log` option that sets `config log` on the ipfw rule. It's something I found myself doing repeatedly after re-applying the nat64 rule in the webui. Having a persistent toggle for it would be great.
Thanks for the

2021-05-05 12:29 UTC, sbeaver-netgate commented
No activity for six months. Is this PR still in progress or should it be closed?

2021-08-10 14:21 UTC, rbgarga commented
@nickwhaley we are working to remove ipfw from pfSense and if we accept this patch we would add an extra ipfw dependency to be removed soon.  Because of that we can't accept this contribution.  Thank you!

2021-08-10 14:21 UTC, closed without merging

2021-08-28 06:48 UTC, imacks commented
@nickwhaley sad to see this PR closed. Is there any chance of providing some docs on this feature?

2021-09-01 01:34 UTC, nickwhaley commented
@imacks If we could use it then I would. But not when IPFW is being used. This needs to be entirely rewritten first.

2021-09-06 19:21 UTC, imacks commented
@nickwhaley it's a pity. I was trying out this PR but couldn't get it to work as @frebib could. Evidently my understanding of ipfw must be wrong.

I have from ISP WAN pppoe as `a:b:c:d::/64` and `1.2.3.4`. I configured nat64 `a:b:c:d::/96` to `100.64.0.0/16` allow embed private ip. WAN pf rule allow any from `100.64.0.0/16` to LAN network (192.168.1.1/24) state none. On LAN pf rule allow any from `a:b:c:d::/96` state none. Ping from outside to `a:b:c:d::c0a8:0101` failed b'cos WAN pf is blocking. ipfw stats shows that it did not filter any packet.

While consolidating to pf is great, having a usable nat64 on pfsense may be many months off. I think many users like me who want to try this PR now would appreciate an example config to get started. Tks!

2021-09-13 18:26 UTC, nickwhaley commented
@imacks This pull request is closed; not months off. The NAT64 module for IPFW is either gone or being removed. IPFW itself is either gone or being removed. PF does not have NAT64 support and moving the NAT64 support from PF in OpenBSD is a large operation that no one is committed to doing. Also, a new UI would have to be made for a different NAT64 implementation regardless, which again, no one is committed to doing.

If you want to run this development version, then there isn't going to be any support for it, if it even still works at all. Would check the PF log to see what is being dropped and make a rule for that. IPFW isn't filtering packets here.