Redirect back to Login Page on Captiveportal Logout
pfsense/pfsense pull request #4496
Opened 2021-01-19 14:27 UTC by nraven777

Currently (i.e when a custom logout page is present) when a user clicks on logout , a window with the  logout message is shown which closes automatically after a few seconds ,  this is both visually unappealing and can close the browser if the user only has the pfsense logout tab open , it therefore  would be a good move to redirect the user back to the login page when they click on logout.

2021-01-19 15:54 UTC, jim-p commented
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

2021-01-23 04:39 UTC, nraven777 commented
Hey @jim-p  ,  could you please review this pull request.

2021-02-22 11:08 UTC, rbgarga approved these changes

2021-02-22 16:39 UTC, jim-p requested changes

2021-02-22 16:39 UTC, jim-p commented on src/usr/local/captiveportal/index.php
> +	header("Location: index.php?zone=".$cpzone);
This should go at the end after the other functions have been executed.

2021-02-23 08:48 UTC, closed without merging