add an option to disable auto-creation of static routes for dpinger
pfsense/pfsense pull request #4551
Opened 2022-01-14 22:42 UTC by luckman212

- [x] Redmine Issue: https://redmine.pfsense.org/issues/2514
- [x] Ready for review

### Summary

Users may NOT want static routes added for every gateway monitor IP.

This has been discussed before, and I've been running for years with this tiny patch. **_No kittens have died._** 🙀 

The original code was written probably over a decade ago, in the era of `apinger` (anyone remember that?)

`apinger` did not bind to an interface, so the static routes were needed, but I don't think they are anymore now that we've got `dpinger`. There are a lot of footguns when adding routes to anycast IPs (which is the suggested best-practice) since they tend to be DNS servers. I would bet somewhere ~50% of all installs just use 8.8.8.8 etc. So your DNS gets hosed if one of your gateways goes down in Multiwan, defeating the entire purpose.

### Evidence

1. Directly from the code [`/etc/inc/gwlb.inc`](https://github.com/pfsense/pfsense/blob/ba815f3d219e5bdf404be859e723db2ff0c9258c/src/etc/inc/gwlb.inc#L240):
<img width=800 src=https://user-images.githubusercontent.com/1992842/149594295-917439de-91b3-499f-943f-57639b1a156e.png>

2. From the [docs](https://docs.netgate.com/pfsense/en/latest/routing/gateway-configure.html):
<img width=600 src=https://user-images.githubusercontent.com/1992842/149594138-053d59e6-d698-4ec3-be60-69107552352f.png>

### Related discussions

- [Changing the monitor IP of a gateway caused all traffic to that IP to go over said gateway, despite not being default - bug? r/PFSENSE](https://www.reddit.com/r/PFSENSE/comments/rcmho8/changing_the_monitor_ip_of_a_gateway_caused_all/)
- [Gateway monitor IPs are being put into the routing table](https://forum.netgate.com/topic/144488/gateway-monitor-ips-are-being-put-into-the-routing-table/19)
- [Setting host as Monitored IP makes it unreachable? | Netgate Forum](https://forum.netgate.com/topic/127191/setting-host-as-monitored-ip-makes-it-unreachable)
- [Bug #2514: static routes for monitor IPs should be removed - pfSense - pfSense bugtracker](https://redmine.pfsense.org/issues/2514)
- [Bug #12608: WireGuard tunnels monitored by dpinger causing system to stop routing completely in certain situations - pfSense Packages - pfSense bugtracker](https://redmine.pfsense.org/issues/12608)

### Testing

Tested on a 5100 running 2.4.x and 2.5.x, as well as a 6100 running pfS+ 22.01 rc.

2022-01-15 00:26 UTC, dennypage commented
> The original code was written probably over a decade ago, in the era of `apinger` (anyone remember that?)

Yes, I do.  :slightly_smiling_face:

2022-01-16 14:29 UTC, luckman212 commented
@dennypage Do you have any thoughts on this PR?

2022-01-17 13:26 UTC, jim-p commented
Why make this a global option instead of a per-gateway option? If users want to do this selectively, it makes more sense to allow them to disable the behavior on a case-by-case basis rather than one single master on/off that forces them to add manual routes for the cases they do want to have routes.

A gateway option to add the static routes that defaults to enabled would be a lot more flexible, IMO.

2022-01-17 13:40 UTC, luckman212 commented
@jim-p Thanks for looking. I thought about that but IMO if they want static routes, shouldn't they be adding those on the proper Static Routes page? 

<img width=400 src=https://user-images.githubusercontent.com/1992842/149778932-d3b2c0d5-e15a-47b0-beb0-be9a36862061.png>

The only use case I could come up with for having it be a per-gateway setting is a PPPoE connection. Because I don't have any to test with, I wasn't sure if the binding was required there for dpinger to do the right thing. Anyway, I'm happy to make the setting per gateway if everyone agrees that's the right thing to do.

2022-01-17 13:43 UTC, jim-p commented
It's not that they don't "belong" there necessarily, but if there is an automatic way to do it, it puts an undue burden on the user for it to be "all or nothing" in cases like this. The more gateways they have, the more of an impact this option would have if they wanted to disable the route for just one gateway out of many.

There could still be a global option but a fine-grained way to control it is more user friendly.

2022-01-17 13:57 UTC, luckman212 commented
Ok, I'll do it.

2022-01-18 21:43 UTC, luckman212 commented
@jim-p I added a per-gateway setting. So this change can be effected using either the original global override or per-gateway now

<img width=600 src=https://user-images.githubusercontent.com/1992842/150023349-8a848909-eec8-411b-9c73-340daca70136.png>

2022-01-21 12:34 UTC, luckman212 commented
Is this ok now? Any other changes you want to see here @jim-p ? Thanks

2022-01-21 13:55 UTC, jim-p commented
Might be a while before I can look it over in detail, we're pretty busy with the 22.01/2.6.0 release testing and such at the moment, but I'll check it out when I have some spare cycles.

2022-01-21 15:08 UTC, luckman212 commented
Ok got it, I was naively hoping it could squeak into 22.01 😊

2022-01-21 15:21 UTC, jim-p commented
Ah, nope, we closed the window on new features a while ago, far too close to get anything else in but significant regressions at this point. But the next release is not too far off (22.05).

2022-02-17 01:04 UTC, luckman212 commented
I've been running 22.05 dev builds now at home (6100) for a week or so. Hoping when the dust from 22.01/2.6 settles this can be considered for a merge!

2022-03-03 14:29 UTC, luckman212 commented
@jim-p Any issues with this? I don't know when the cutoff is for 22.05 but it seems like it's going to be soon. Could you let me know if you need any more changes?

2022-03-03 14:51 UTC, jim-p requested changes
Just some minor grammar nits to correct, looks OK otherwise, thanks!

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_advanced_misc.php
> +	'Do not add static routes for gateway monitor IPs',
Change `IPs` to `IP Addresses`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_advanced_misc.php
> +))->setHelp('By default, static routes are added for gateway monitor IPs '.
Change `IPs` to `IP Addresses`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_advanced_misc.php
> +	'to ensure traffic to the monitor IP leaves via the correct interface. '.
Change `IP` to `IP Address`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_gateways_edit.php
> +	'Do not add static route for gateway monitor IP via the chosen interface',
Change `IP` to `IP Address`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_gateways_edit.php
> +))->setHelp('By default, static routes are added for gateway monitor IPs '.
Change `IPs` to `IP Addresses`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_gateways_edit.php
> +	'to ensure traffic to the monitor IP leaves via the correct interface. '.
Change `IP` to `IP Address`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_gateways_edit.php
> +))->setHelp('By default, static routes are added for gateway monitor IPs '.
Change `, static routes are added` to `the firewall adds static routes`

2022-03-03 14:51 UTC, jim-p commented on src/usr/local/www/system_advanced_misc.php
> +))->setHelp('By default, static routes are added for gateway monitor IPs '.
Change `, static routes are added` to `the firewall adds static routes`

2022-03-04 03:43 UTC, luckman212 commented
@jim-p Ok, I think I got all of them with this last commit. Hope you don't mind that I spelled "addresses" with a lowercase "a". Seemed like the right thing to do.

2022-03-04 13:27 UTC, jim-p approved these changes

2022-03-04 13:30 UTC, merged

2022-03-05 14:18 UTC, luckman212 commented on src/usr/local/www/system_gateways_edit.php
> +$form->add($section);
Sorry, I don't know how this extra `$form->add($section);` snuck in.

2022-06-01 17:58 UTC, luckman212 commented
@jim-p Sorry for the last minute message here, but as I was working on the v2 of this patch, I realized a critical error slipped through. 

The global `dpinger_dont_add_static_routes` config flag never gets properly set in config.xml with the currently merged version of this patch, because of a missing piece of code in `/usr/local/pfSense/include/www/system_advanced_misc.inc`:

```php
if ($post['dpinger_dont_add_static_routes'] == "yes") {
    $config['system']['dpinger_dont_add_static_routes'] = true;
} else {
    unset($config['system']['dpinger_dont_add_static_routes']);
}
```
Since this is already merged I don't think I can push more changes to it, right? I have the corrected code at #4590 but not sure how to get that pulled in.